### PR TITLE
Added support for Adobe Analytics Report API

### PR DESCRIPTION
**Pull request by SarjuHansaliya**

### CODE REVIEW

**Review by Rafase282 — COMMENTED** [review]
Everything looks good. I would like to see a test run.

**Comment by SarjuHansaliya** [comment]
@Rafase282 How would like to do that ?

**Comment by Rafase282** [comment]
@SarjuHansaliya we could use [Glitch](https://glitch.com/edit/#!/slacknpodio)

**Comment by flyblackbox** [comment]
I think Glitch would be best so we can openly collaborate. @SarjuHansaliya @Rafase282

**Comment by SarjuHansaliya** [comment]
Sorry @Rafase282 @flyblackbox  for replying late. 
Yeah we will use glitch. Its too late night here. May be we can do something tomorrow ?
I will be online in slack tomorrow on your time.

**Pull request merged**
